import type {Metadata} from "next";
import {Inter} from "next/font/google";
import Head from "next/head";
import 'bootstrap-icons/font/bootstrap-icons.min.css'

// import '@/styles/reset.css'
import GoogleAnalytics from "@/components/google/GoogleAnalytics";
import './globals.css'
import BootstrapJs from "@/components/bootstrap/BootstrapJs";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Travel At",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.ico",
    },
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <Head>
            <meta charSet="utf-8"/>
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
            <meta name="description" content=""/>
            <meta name="author" content=""/>
        </Head>
        <GoogleAnalytics/>
        <BootstrapJs />
        <body className={inter.className}>
        {children}{/*
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Travel At 2024</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>*/}
        </body>
        </html>
    );
}
