import type {Metadata} from "next";
import {Inter} from "next/font/google";
import Head from "next/head";
import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from '@vercel/speed-insights/next';
import 'bootstrap-icons/font/bootstrap-icons.min.css'

import './globals.css'
import GoogleAnalytics from "@/components/google/GoogleAnalytics";
import BootstrapJs from "@/components/bootstrap/BootstrapJs";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Travel At",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.ico",
    },
    verification: {
        google: "V7Iq6K7jhgusFStXzd9RNP01aoDXXl7vOod5aomf0Mg"
    }
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <Head>
            <meta charSet="utf-8"/>
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
            <meta name="description" content=""/>
            <meta name="author" content=""/>
        </Head>
        <GoogleAnalytics/>
        <BootstrapJs/>
        <body className={inter.className}>
        {children}
        <Analytics />
        <SpeedInsights />
        </body>
        </html>
    );
}
